{% set version = "0.4.3" %}

package:
  name: juliacall
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/juliacall/juliacall-{{ version }}.tar.gz
  sha256: ff81c152831775bbbb26b7752a7825d1de2fd6c154f71ffc22338996b4faac07

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cjdoris/PythonCall.jl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Julia and Python in seamless harmony'
  description: |
    juliacall is a package for calling Julia code from Python with a simple syntax. It has
    a symmetric interface, with intuitive and flexible conversion of data in both directions,
    including fast non-copying conversion of data structures.
  doc_url: https://cjdoris.github.io/PythonCall.jl/stable
  dev_url: https://github.com/cjdoris/PythonCall.jl

extra:
  recipe-maintainers:
    - cjdoris
